# Generated by Django 6.0.5 on 2026-06-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=True, help_text='For parents, it should be set to True by default. For doctors, it should change to True only after admin verification.'),
        ),
    ]
