# Generated by Django 6.0.5 on 2026-05-26 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(help_text='Credentials yahin bheje jayenge', max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('pmdc_number', models.CharField(max_length=50, unique=True)),
                ('specialty', models.CharField(choices=[('pediatric_homeopath', 'Pediatric Homeopath'), ('child_specialist', 'Child Specialist'), ('organic_medicine', 'Organic Medicine'), ('homeopathic_consultant', 'Homeopathic Consultant')], max_length=30)),
                ('experience_years', models.PositiveIntegerField()),
                ('clinic_address', models.TextField(blank=True)),
                ('consultation_fee', models.PositiveIntegerField(default=1000, help_text='Rs. mein')),
                ('pmdc_license', models.FileField(upload_to='doctor_docs/pmdc/')),
                ('cnic_front', models.FileField(upload_to='doctor_docs/cnic/')),
                ('cnic_back', models.FileField(upload_to='doctor_docs/cnic/')),
                ('degree', models.FileField(upload_to='doctor_docs/degree/')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='doctor_docs/photos/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('rejection_reason', models.TextField(blank=True)),
                ('generated_password', models.CharField(blank=True, max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('linked_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor Application',
                'verbose_name_plural': 'Doctor Applications',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('pmdc_number', models.CharField(max_length=50, unique=True)),
                ('specialty', models.CharField(max_length=50)),
                ('experience_years', models.PositiveIntegerField()),
                ('clinic_address', models.TextField(blank=True)),
                ('consultation_fee', models.PositiveIntegerField(default=1000)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='doctor_profiles/')),
                ('bio', models.TextField(blank=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('total_patients', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor Profile',
                'verbose_name_plural': 'Doctor Profiles',
            },
        ),
    ]
