# Generated by Django 6.0.5 on 2026-06-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorapplication',
            name='city',
            field=models.CharField(blank=True, default='Karachi', help_text='City name (e.g., Karachi, Lahore)', max_length=100),
        ),
        migrations.AddField(
            model_name='doctorapplication',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='GPS latitude of clinic location', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='doctorapplication',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='GPS longitude of clinic location', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='city',
            field=models.CharField(blank=True, default='Karachi', help_text='City name', max_length=100),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='GPS latitude of clinic location', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='GPS longitude of clinic location', max_digits=10, null=True),
        ),
    ]
