# Generated by Django 6.0.5 on 2026-06-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctorapplication_city_doctorapplication_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorapplication',
            name='consultation_fee',
            field=models.PositiveIntegerField(default=1000, help_text='Amount in Rs.'),
        ),
        migrations.AlterField(
            model_name='doctorapplication',
            name='email',
            field=models.EmailField(help_text='Credentials will be sent here', max_length=254, unique=True),
        ),
    ]
