# Generated by Django 6.0.5 on 2026-06-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_doctorapplication_consultation_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorapplication',
            name='email',
            field=models.EmailField(help_text='Credentials will be sent to this email', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='doctorapplication',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='GPS latitude of clinic location', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='doctorapplication',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='GPS longitude of clinic location', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='GPS latitude of clinic location', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='GPS longitude of clinic location', max_digits=15, null=True),
        ),
    ]
