# Generated by Django 6.0.5 on 2026-06-12 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
        ('doctors', '0003_alter_doctorapplication_consultation_fee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='against_doctor',
            field=models.ForeignKey(blank=True, help_text='If there is a complaint against the doctor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_against', to='doctors.doctorprofile'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='against_user',
            field=models.ForeignKey(blank=True, help_text='If there is a complaint against the user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_against_me', to=settings.AUTH_USER_MODEL),
        ),
    ]
